# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-09 13:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('REST', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rest',
            old_name='linenos',
            new_name='alive',
        ),
        migrations.RenameField(
            model_name='rest',
            old_name='code',
            new_name='designation',
        ),
        migrations.RenameField(
            model_name='rest',
            old_name='title',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='rest',
            name='highlighted',
        ),
        migrations.RemoveField(
            model_name='rest',
            name='language',
        ),
        migrations.RemoveField(
            model_name='rest',
            name='style',
        ),
        migrations.AlterField(
            model_name='rest',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to=settings.AUTH_USER_MODEL),
        ),
    ]
