# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-11 08:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('REST', '0002_auto_20160209_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='rest',
            name='data',
            field=models.FileField(default='', upload_to='uploads/'),
        ),
    ]
